# Induction

In this notebook, we will just use the basic functions of Numpy, i.e., array initialization, mathematical operations, and things like that. 

**What is Numpy and why should we use it?**

Before we get into the code, I would like to talk a little bit about this module. Numpy, which stands for Numerical Python, is basically an open-source Python module allowing us to work on numbers and multidimensional arrays. There are at least 3 advantages we can get by using this module as compared to the standard Python list. 

First, it provides a lot more flexibilities when it comes to numerical computation and array manipulation. 

Second, Numpy is faster, and third, it consumes less memory. 

The last two mentioned advantages are basically because most of the backend of Numpy uses C programming language.

# 1. Numpy Installation

In [1]:
!pip install numpy

In [2]:
import numpy as np
np.__version__

'1.26.4'

# 2. Array Initialization

In [3]:
# Codeblock 3
np.asarray([7,6,5,4,3,2])

array([7, 6, 5, 4, 3, 2])

As the above code is run, it is going to return an output which looks like the one shown in Figure 3. 

If you put that array inside the `print() function`, the output is going to look somewhat different. In the figure below you can see that the text “array” as well as **the commas disappear**. Nevertheless, keep in mind that it is actually just the matter of representation.

In [4]:
# Codeblock 4
print(np.asarray([7,6,5,4,3,2]))

[7 6 5 4 3 2]


The above behavior is actually different from Python list. If we try to print it out, the result is going to look like as below regardless the use of the `print() function`. We can see in the figure that all elements are separated by a comma while at the same time no “array” text is printed.

In [5]:
### Returns the exact same result.
print([7,6,5,4,3,2])

[7, 6, 5, 4, 3, 2]


Another difference between `Numpy array` and `Python list` can also be seen when we try to print out 2D array.

You can see below that `Numpy array` is automatically printed as **rows and columns**, while Python list is not.

In [6]:
print(np.asarray([[7,6,5,4,3,2],
                [9,8,7,6,5,4]]), end='\n\n')
print([[7,6,5,4,3,2],
      [9,8,7,6,5,4]])

[[7 6 5 4 3 2]
 [9 8 7 6 5 4]]

[[7, 6, 5, 4, 3, 2], [9, 8, 7, 6, 5, 4]]


Both `np.array()` and `np.asarray()` are used to convert a list into Numpy array. 

To do the reverse, we can use the `tolist()` method.

In [7]:
A= [2,4,6,8]
B= np.array(A)  # Convert to Numpy array.
C= B.tolist()   # Convert to Python list.

print(B)
print(C)

[2 4 6 8]
[2, 4, 6, 8]


In case you’re not sure whether a variable contains a list or Numpy array, we can use the `type() function` to check without needing to display the entire content of that variable. By the way the term “ndarray” in the resulting output basically stands for N-dimensional array.

In [8]:
print('type(A):', type(A))
print('type(B):', type(B))
print('type(C):', type(C))

type(A): <class 'list'>
type(B): <class 'numpy.ndarray'>
type(C): <class 'list'>


The last thing I want to show you in this chapter is that we can `initialize a Numpy array automatically` based on the data in a txt file. 

The function we can use for this is `np.genfromtxt()`. 

<div style="text-align: center"><img src="https://miro.medium.com/v2/resize:fit:1032/format:webp/1*2j8bayfXvU9bXTgMi8csng.png" width="100%" heigh="100%" alt="Retrieve&Re-Rank pipeline"></div>

# 3. Numpy Array Limitation

Before we discuss all the things possible to be done using Numpy, I will tell you what this module can not do. 

In Codeblock 10 below, I put multiple values of different datatypes in a Python list, and it seems like the list is able to handle the values properly.

In [9]:
# Codeblock 10
D = [2, 'Hello', True, 9.886]
D

[2, 'Hello', True, 9.886]

If we convert list D into Numpy array, all the values inside will automatically turn into string even after we convert it back to list again.

In [10]:
# Codeblock 11
print(np.array(D))
print(np.array(D).tolist())

['2' 'Hello' 'True' '9.886']
['2', 'Hello', 'True', '9.886']


The above demonstration basically signifies the disadvantage of using Numpy array: it is unable to store elements of multiple datatypes. However, there is actually a reason behind this behavior, in which it allows array computations to be a lot faster and memory efficient as compared to Python list. 

# 4. Computational Speed and Memory Usage

In order to see the time required for Numpy array and Python list to perform the exact same operation, we need to import the `time` module and also initializing the arrays to be used.

In [11]:
# Codeblock 12
import time

E = [123] * 9999999
F = np.array(E, dtype='int8')

The idea of this experiment is very simple, all I want to do is just to sum all values in list E and array F using `sum()` and `np.sum()`. Afterwards, I will print out the computation time. The two functions I write below, namely `summation_python_sum()` is the one that uses Python’s `sum()` function, while the `summation_numpy_sum()` performs the operation using `np.sum()`.

In [12]:
# Codeblock 13
def summation_python_sum(arr):
    start_time = time.time()
    sum(arr)
    end_time = time.time()

    total_time = end_time - start_time
    return total_time
    
def summation_numpy_sum(arr):
    start_time = time.time()
    np.sum(arr)
    end_time = time.time()

    total_time = end_time - start_time
    return total_time

As the two functions above have been declared, now that we can start our experiment by running the Codeblock 14 below.

In [13]:
# Codeblock 14
print('Python list with sum()\t\t: ', summation_python_sum(E), 'sec')
print('Python list with np.sum()\t: ', summation_numpy_sum(E), 'sec')
print('Numpy array with sum()\t\t: ', summation_python_sum(F), 'sec')
print('Numpy array with np.sum()\t: ', summation_numpy_sum(F), 'sec')

Python list with sum()		:  0.0928659439086914 sec
Python list with np.sum()	:  0.9854695796966553 sec
Numpy array with sum()		:  3.4738502502441406 sec
Numpy array with np.sum()	:  0.007088184356689453 sec


According to the results above, we can see that Numpy array works much faster than the others especially when it is paired with Numpy function (0.007 seconds). The second fastest result is obtained when Python list is executed with Python function as well (0.17 seconds). However, in this case it is still around 23 times slower than Numpy. One thing we need to pay attention to is that I think we should avoid mixing either Python functions with Numpy arrays or Python lists with Numpy functions because it causes the processing time to get even slower.

# Memory Usage

That was all about the computational speed, now let’s see how much memory do `list E` and `array F` take. We can do that by executing the codeblock below.

In [14]:
# Codeblock 15
import sys

print('E (Python list):', sys.getsizeof(E), 'bytes')
print('F (Numpy array):', sys.getsizeof(F), 'bytes')

E (Python list): 80000048 bytes
F (Numpy array): 10000111 bytes


As you can see the above output, list E takes up 8 times more memory as compared to array F. You might probably have noticed in Codeblock 12 that I used int8 for the dtype parameter, which essentially stands for 8-bit integer. In this case I decided to use only 8 bits since the numbers in our array is considerably small. Numpy indeed allows us to specify such details in the datatype, making it more efficient in terms of memory usage.

# 5. Datatypes
We can check the datatype of a Numpy array by printing out its dtype attribute. In the output below, we can see that the `datatype` of array `F` is `int8`, which is exactly the same as what we set earlier. Meanwhile, remember that previously we did not specify the datatype for array B. In such a case, Numpy usually will set it to `int32`.

In [15]:
# Codeblock 16
print(B.dtype)
print(F.dtype)

int64
int8


The other array datatypes that I frequently use are float and boolean. In the case of float, you can just pass an array of non-integers into `np.array()` and it will automatically set the datatype to `float64`.

In [16]:
# Codeblock 17
print(np.array([5, 5, 5, 5.3, 5]).dtype)
print(np.array([True, True, False]).dtype)

float64
bool


**The Integer and Float Datatypes**

Now I would like to talk a bit deeper about integers and floats. As I have mentioned earlier, the number written after `int` basically denotes the number of bits used to represent an integer value. Let’s take a look at this example: suppose we have the number 26. In binary, 26 is equivalent to 11010, in which it is represented using 5 binary digits, i.e., 5 bits. If we store this number into Numpy array with `int8` datatype, the number will be stored as 00011010.

The binary sequence of 00011010 itself is basically still equivalent to 26, except that it is now represented in 8 bits. if you use `int16` instead, then the number will be written as 00000000 00011010. According to this fact, it now mkes sense that larger number of bits requires more memory even when the stored numbers remain the same.


Furthermore, you also need to know that smaller number of bits causes us to have a more limited range of numbers. The maximum and minimum number that `int8` can store is 127 and -128, respectively. The first digit is used to denote the sign (i.e., either positive or negative) while the rest are responsible to store the magnitude. Meanwhile, in the case of float, smaller bit makes the number to be stored has less precision.


We can see the details of each integer datatype using the following code.

In [17]:
# Codeblock 18
print(np.iinfo(np.int8))
print(np.iinfo(np.int16))
print(np.iinfo(np.int32))
print(np.iinfo(np.int64))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



The similar information can also be obtained for float datatypes using `np.finfo()`.

In [18]:
# Codeblock 19
print(np.finfo(np.float16))
print(np.finfo(np.float32))
print(np.finfo(np.float64))

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------

Machine parameters for float64
---

# 6. Indexing and Slicing

In many cases, indexing and slicing a Numpy array is similar to that of Python list. To demonstrate this, let’s consider the following array.

In [19]:
# Codeblock 20
G = np.array([9, 7, 5, 6, 4, 8, 2, 6, 9, 5, 2, 4, 1, 4])

I will perform variety of indexing and slicing techniques on array `G` in Codeblock 21.

In [20]:
# Codeblock 21
print('G[7]\t\t:', G[7])        #(1)
print('G[-2]\t\t:', G[-2])      #(2)
print('G[:3]\t\t:', G[:3])      #(3)
print('G[3:]\t\t:', G[3:])      #(4)
print('G[2:6]\t\t:', G[2:6])    #(5)
print('G[1:7:2]\t:', G[1:7:2])  #(6)
print('G[::3]\t\t:', G[::3])    #(7)

G[7]		: 6
G[-2]		: 1
G[:3]		: [9 7 5]
G[3:]		: [6 4 8 2 6 9 5 2 4 1 4]
G[2:6]		: [5 6 4 8]
G[1:7:2]	: [7 6 8]
G[::3]		: [9 6 2 5 1]


**Here is what the above codes actually do:**

1. G[7] → Take the 7-th element of array G.
1. G[-2] → Take the 2-nd element from behind.
1. G[:3] → Take the first 3 elements.
1. G[3:] → Take all elements except the first 3. We will start from G[3] all the way to the end. Remember that array index starts from 0.
1. G[2:6] → Take elements from index 2 to 5 (index 6 is not included).
1. G[1:7:2] → Take elements from index 1 to 6 with the step of 2.
1. G[::3] → Take all elements with step 3.


The above demonstration regarding indexing and slicing can also be implemented on a Python list. There is actually one technique that is exclusively applicable for Numpy array: indexing with another array. In the example below, we take the value of index 6, 4, 5, 7, and 3 from array G.

In [21]:
# Codeblock 22
H = np.array([6,4,5,7,4,3])
print('G[H]\t:', G[H])

G[H]	: [2 4 8 6 4 6]


# Credit:

https://python.plainenglish.io/mastering-numpy-a-comprehensive-guide-to-efficient-array-processing-part-1-2-d55efd851234