# Induction

In this notebook, we will just use the basic functions of Numpy, i.e., array initialization, mathematical operations, and things like that. 

**What is Numpy and why should we use it?**

Before we get into the code, I would like to talk a little bit about this module. Numpy, which stands for Numerical Python, is basically an open-source Python module allowing us to work on numbers and multidimensional arrays. There are at least 3 advantages we can get by using this module as compared to the standard Python list. 

First, it provides a lot more flexibilities when it comes to numerical computation and array manipulation. 

Second, Numpy is faster, and third, it consumes less memory. 

The last two mentioned advantages are basically because most of the backend of Numpy uses C programming language.

# 1. Numpy Installation

In [1]:
!pip install numpy

In [2]:
import numpy as np
np.__version__

'1.26.4'

# 2. Array Initialization

In [3]:
# Codeblock 3
np.asarray([7,6,5,4,3,2])

array([7, 6, 5, 4, 3, 2])

As the above code is run, it is going to return an output which looks like the one shown in Figure 3. 

If you put that array inside the `print() function`, the output is going to look somewhat different. In the figure below you can see that the text “array” as well as **the commas disappear**. Nevertheless, keep in mind that it is actually just the matter of representation.

In [4]:
# Codeblock 4
print(np.asarray([7,6,5,4,3,2]))

[7 6 5 4 3 2]


The above behavior is actually different from Python list. If we try to print it out, the result is going to look like as below regardless the use of the `print() function`. We can see in the figure that all elements are separated by a comma while at the same time no “array” text is printed.

In [5]:
### Returns the exact same result.
print([7,6,5,4,3,2])

[7, 6, 5, 4, 3, 2]


Another difference between `Numpy array` and `Python list` can also be seen when we try to print out 2D array.

You can see below that `Numpy array` is automatically printed as **rows and columns**, while Python list is not.

In [6]:
print(np.asarray([[7,6,5,4,3,2],
                [9,8,7,6,5,4]]), end='\n\n')
print([[7,6,5,4,3,2],
      [9,8,7,6,5,4]])

[[7 6 5 4 3 2]
 [9 8 7 6 5 4]]

[[7, 6, 5, 4, 3, 2], [9, 8, 7, 6, 5, 4]]


Both `np.array()` and `np.asarray()` are used to convert a list into Numpy array. 

To do the reverse, we can use the `tolist()` method.

In [7]:
A= [2,4,6,8]
B= np.array(A)  # Convert to Numpy array.
C= B.tolist()   # Convert to Python list.

print(B)
print(C)

[2 4 6 8]
[2, 4, 6, 8]


In case you’re not sure whether a variable contains a list or Numpy array, we can use the `type() function` to check without needing to display the entire content of that variable. By the way the term “ndarray” in the resulting output basically stands for N-dimensional array.

In [8]:
print('type(A):', type(A))
print('type(B):', type(B))
print('type(C):', type(C))

type(A): <class 'list'>
type(B): <class 'numpy.ndarray'>
type(C): <class 'list'>


The last thing I want to show you in this chapter is that we can `initialize a Numpy array automatically` based on the data in a txt file. 

The function we can use for this is `np.genfromtxt()`. 

<div style="text-align: center"><img src="https://miro.medium.com/v2/resize:fit:1032/format:webp/1*2j8bayfXvU9bXTgMi8csng.png" width="100%" heigh="100%" alt="Retrieve&Re-Rank pipeline"></div>

# Credit:

https://python.plainenglish.io/mastering-numpy-a-comprehensive-guide-to-efficient-array-processing-part-1-2-d55efd851234