# Induction

In this notebook, we will just use the basic functions of Numpy, i.e., array initialization, mathematical operations, and things like that. 

**What is Numpy and why should we use it?**

Before we get into the code, I would like to talk a little bit about this module. Numpy, which stands for Numerical Python, is basically an open-source Python module allowing us to work on numbers and multidimensional arrays. There are at least 3 advantages we can get by using this module as compared to the standard Python list. 

First, it provides a lot more flexibilities when it comes to numerical computation and array manipulation. 

Second, Numpy is faster, and third, it consumes less memory. 

The last two mentioned advantages are basically because most of the backend of Numpy uses C programming language.

# 1. Numpy Installation

In [1]:
!pip install numpy

In [2]:
import numpy as np
np.__version__

'1.26.4'

# 2. Array Initialization

In [3]:
# Codeblock 3
np.asarray([7,6,5,4,3,2])

array([7, 6, 5, 4, 3, 2])

As the above code is run, it is going to return an output which looks like the one shown in Figure 3. 

If you put that array inside the `print() function`, the output is going to look somewhat different. In the figure below you can see that the text “array” as well as **the commas disappear**. Nevertheless, keep in mind that it is actually just the matter of representation.

In [4]:
# Codeblock 4
print(np.asarray([7,6,5,4,3,2]))

[7 6 5 4 3 2]


The above behavior is actually different from Python list. If we try to print it out, the result is going to look like as below regardless the use of the `print() function`. We can see in the figure that all elements are separated by a comma while at the same time no “array” text is printed.

In [5]:
### Returns the exact same result.
print([7,6,5,4,3,2])

[7, 6, 5, 4, 3, 2]


Another difference between `Numpy array` and `Python list` can also be seen when we try to print out 2D array.

You can see below that `Numpy array` is automatically printed as **rows and columns**, while Python list is not.

In [6]:
print(np.asarray([[7,6,5,4,3,2],
                [9,8,7,6,5,4]]), end='\n\n')
print([[7,6,5,4,3,2],
      [9,8,7,6,5,4]])

[[7 6 5 4 3 2]
 [9 8 7 6 5 4]]

[[7, 6, 5, 4, 3, 2], [9, 8, 7, 6, 5, 4]]


Both `np.array()` and `np.asarray()` are used to convert a list into Numpy array. 

To do the reverse, we can use the `tolist()` method.

In [7]:
A= [2,4,6,8]
B= np.array(A)  # Convert to Numpy array.
C= B.tolist()   # Convert to Python list.

print(B)
print(C)

[2 4 6 8]
[2, 4, 6, 8]


In case you’re not sure whether a variable contains a list or Numpy array, we can use the `type() function` to check without needing to display the entire content of that variable. By the way the term “ndarray” in the resulting output basically stands for N-dimensional array.

In [8]:
print('type(A):', type(A))
print('type(B):', type(B))
print('type(C):', type(C))

type(A): <class 'list'>
type(B): <class 'numpy.ndarray'>
type(C): <class 'list'>


The last thing I want to show you in this chapter is that we can `initialize a Numpy array automatically` based on the data in a txt file. 

The function we can use for this is `np.genfromtxt()`. 

<div style="text-align: center"><img src="https://miro.medium.com/v2/resize:fit:1032/format:webp/1*2j8bayfXvU9bXTgMi8csng.png" width="100%" heigh="100%" alt="Retrieve&Re-Rank pipeline"></div>

# 3. Numpy Array Limitation

Before we discuss all the things possible to be done using Numpy, I will tell you what this module can not do. 

In Codeblock 10 below, I put multiple values of different datatypes in a Python list, and it seems like the list is able to handle the values properly.

In [9]:
# Codeblock 10
D = [2, 'Hello', True, 9.886]
D

[2, 'Hello', True, 9.886]

If we convert list D into Numpy array, all the values inside will automatically turn into string even after we convert it back to list again.

In [10]:
# Codeblock 11
print(np.array(D))
print(np.array(D).tolist())

['2' 'Hello' 'True' '9.886']
['2', 'Hello', 'True', '9.886']


The above demonstration basically signifies the disadvantage of using Numpy array: it is unable to store elements of multiple datatypes. However, there is actually a reason behind this behavior, in which it allows array computations to be a lot faster and memory efficient as compared to Python list. 

# 4. Computational Speed and Memory Usage

In order to see the time required for Numpy array and Python list to perform the exact same operation, we need to import the `time` module and also initializing the arrays to be used.

In [11]:
# Codeblock 12
import time

E = [123] * 9999999
F = np.array(E, dtype='int8')

The idea of this experiment is very simple, all I want to do is just to sum all values in list E and array F using `sum()` and `np.sum()`. Afterwards, I will print out the computation time. The two functions I write below, namely `summation_python_sum()` is the one that uses Python’s `sum()` function, while the `summation_numpy_sum()` performs the operation using `np.sum()`.

In [12]:
# Codeblock 13
def summation_python_sum(arr):
    start_time = time.time()
    sum(arr)
    end_time = time.time()

    total_time = end_time - start_time
    return total_time
    
def summation_numpy_sum(arr):
    start_time = time.time()
    np.sum(arr)
    end_time = time.time()

    total_time = end_time - start_time
    return total_time

As the two functions above have been declared, now that we can start our experiment by running the Codeblock 14 below.

In [13]:
# Codeblock 14
print('Python list with sum()\t\t: ', summation_python_sum(E), 'sec')
print('Python list with np.sum()\t: ', summation_numpy_sum(E), 'sec')
print('Numpy array with sum()\t\t: ', summation_python_sum(F), 'sec')
print('Numpy array with np.sum()\t: ', summation_numpy_sum(F), 'sec')

Python list with sum()		:  0.09184861183166504 sec
Python list with np.sum()	:  1.0011801719665527 sec
Numpy array with sum()		:  3.457169532775879 sec
Numpy array with np.sum()	:  0.006346940994262695 sec


According to the results above, we can see that Numpy array works much faster than the others especially when it is paired with Numpy function (0.007 seconds). The second fastest result is obtained when Python list is executed with Python function as well (0.17 seconds). However, in this case it is still around 23 times slower than Numpy. One thing we need to pay attention to is that I think we should avoid mixing either Python functions with Numpy arrays or Python lists with Numpy functions because it causes the processing time to get even slower.

# Memory Usage

That was all about the computational speed, now let’s see how much memory do `list E` and `array F` take. We can do that by executing the codeblock below.

In [14]:
# Codeblock 15
import sys

print('E (Python list):', sys.getsizeof(E), 'bytes')
print('F (Numpy array):', sys.getsizeof(F), 'bytes')

E (Python list): 80000048 bytes
F (Numpy array): 10000111 bytes


As you can see the above output, list E takes up 8 times more memory as compared to array F. You might probably have noticed in Codeblock 12 that I used int8 for the dtype parameter, which essentially stands for 8-bit integer. In this case I decided to use only 8 bits since the numbers in our array is considerably small. Numpy indeed allows us to specify such details in the datatype, making it more efficient in terms of memory usage.

# 5. Datatypes
We can check the datatype of a Numpy array by printing out its dtype attribute. In the output below, we can see that the `datatype` of array `F` is `int8`, which is exactly the same as what we set earlier. Meanwhile, remember that previously we did not specify the datatype for array B. In such a case, Numpy usually will set it to `int32`.

In [15]:
# Codeblock 16
print(B.dtype)
print(F.dtype)

int64
int8


The other array datatypes that I frequently use are float and boolean. In the case of float, you can just pass an array of non-integers into `np.array()` and it will automatically set the datatype to `float64`.

In [16]:
# Codeblock 17
print(np.array([5, 5, 5, 5.3, 5]).dtype)
print(np.array([True, True, False]).dtype)

float64
bool


**The Integer and Float Datatypes**

Now I would like to talk a bit deeper about integers and floats. As I have mentioned earlier, the number written after `int` basically denotes the number of bits used to represent an integer value. Let’s take a look at this example: suppose we have the number 26. In binary, 26 is equivalent to 11010, in which it is represented using 5 binary digits, i.e., 5 bits. If we store this number into Numpy array with `int8` datatype, the number will be stored as 00011010.

The binary sequence of 00011010 itself is basically still equivalent to 26, except that it is now represented in 8 bits. if you use `int16` instead, then the number will be written as 00000000 00011010. According to this fact, it now mkes sense that larger number of bits requires more memory even when the stored numbers remain the same.


Furthermore, you also need to know that smaller number of bits causes us to have a more limited range of numbers. The maximum and minimum number that `int8` can store is 127 and -128, respectively. The first digit is used to denote the sign (i.e., either positive or negative) while the rest are responsible to store the magnitude. Meanwhile, in the case of float, smaller bit makes the number to be stored has less precision.


We can see the details of each integer datatype using the following code.

In [17]:
# Codeblock 18
print(np.iinfo(np.int8))
print(np.iinfo(np.int16))
print(np.iinfo(np.int32))
print(np.iinfo(np.int64))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



The similar information can also be obtained for float datatypes using `np.finfo()`.

In [18]:
# Codeblock 19
print(np.finfo(np.float16))
print(np.finfo(np.float32))
print(np.finfo(np.float64))

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------

Machine parameters for float64
---

# 6. Indexing and Slicing

In many cases, indexing and slicing a Numpy array is similar to that of Python list. To demonstrate this, let’s consider the following array.

In [19]:
# Codeblock 20
G = np.array([9, 7, 5, 6, 4, 8, 2, 6, 9, 5, 2, 4, 1, 4])

I will perform variety of indexing and slicing techniques on array `G` in Codeblock 21.

In [20]:
# Codeblock 21
print('G[7]\t\t:', G[7])        #(1)
print('G[-2]\t\t:', G[-2])      #(2)
print('G[:3]\t\t:', G[:3])      #(3)
print('G[3:]\t\t:', G[3:])      #(4)
print('G[2:6]\t\t:', G[2:6])    #(5)
print('G[1:7:2]\t:', G[1:7:2])  #(6)
print('G[::3]\t\t:', G[::3])    #(7)

G[7]		: 6
G[-2]		: 1
G[:3]		: [9 7 5]
G[3:]		: [6 4 8 2 6 9 5 2 4 1 4]
G[2:6]		: [5 6 4 8]
G[1:7:2]	: [7 6 8]
G[::3]		: [9 6 2 5 1]


**Here is what the above codes actually do:**

1. G[7] → Take the 7-th element of array G.
1. G[-2] → Take the 2-nd element from behind.
1. G[:3] → Take the first 3 elements.
1. G[3:] → Take all elements except the first 3. We will start from G[3] all the way to the end. Remember that array index starts from 0.
1. G[2:6] → Take elements from index 2 to 5 (index 6 is not included).
1. G[1:7:2] → Take elements from index 1 to 6 with the step of 2.
1. G[::3] → Take all elements with step 3.


The above demonstration regarding indexing and slicing can also be implemented on a Python list. There is actually one technique that is exclusively applicable for Numpy array: indexing with another array. In the example below, we take the value of index 6, 4, 5, 7, and 3 from array G.

In [21]:
# Codeblock 22
H = np.array([6,4,5,7,4,3])
print('G[H]\t:', G[H])

G[H]	: [2 4 8 6 4 6]


Multidimensional Arrays
The superiority of Numpy arrays over Python lists when it comes to indexing and slicing can clearly be seen especially when we are working with the multidimensional ones. The following examples in this chapter won’t work on lists.

Now let’s initialize a `2D array` first.

In [22]:
# Codeblock 23
I = np.array([[3, 1, 5, 7], 
              [2, 5, 3, 2], 
              [3, 8, 5, 9],
              [4, 8, 2, 6]])

print(I)

[[3 1 5 7]
 [2 5 3 2]
 [3 8 5 9]
 [4 8 2 6]]


In order to take the 0th row and 2nd column (number 5), we can use the code in Codeblock 24. The idea is simple, what we need to do is just to write down the row and column number to be selected.

In [23]:
# Codeblock 24
I[0,2]

5

Next, we can take `the first 2 rows and the first 3 columns` using Codeblock 25.

In [24]:
# Codeblock 25
I[:2,:3]

array([[3, 1, 5],
       [2, 5, 3]])

If you want to take the entire row or column, you can simply use `:`. In the following example, what I want to do is to take the entire row of column 1 to 3 (the third index is not included).

In [25]:
# Codeblock 26
I[:,1:3]

array([[1, 5],
       [5, 3],
       [8, 5],
       [8, 2]])

The following example is similar to the previous one, except that here we exclude the last row.

In [26]:
# Codeblock 27
I[:-1,1:3]

array([[1, 5],
       [5, 3],
       [8, 5]])

Indexing with another array or list also works for 2D arrays. In the example below I take the first 3 columns from row 0 and 2.

In [27]:
# Codeblock 28
I[[0,2], :3]

array([[3, 1, 5],
       [3, 8, 5]])

Lastly, below is what the result looks like when we take elements from `“coordinate”` [0,0], [1,1] and [2,2] `simultaneously`.

In [28]:
# Codeblock 29
I[[0,1,2], [0,1,2]]

array([3, 5, 5])

# 7. Array Generation Functions

Numpy allows us to generate array of specific numbers easily. I will start with `np.ones()` and `np.zeros()`. The way to use these functions are basically the same, except that the former generates an array containing 1s, while the latter produces array filled with 0s. All we need to do is just to specify the desired shape for the argument. In Codeblock 30 I demonstrate the use of np.ones() for creating a one-dimensional array comprising of 10 elements.

In [29]:
# Codeblock 30
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

To create a two-dimensional array, the argument needs to be in form of a tuple. Here I create all-zero array with 4 rows and 3 columns.

In [30]:
# Codeblock 31
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Not only one and two-dimensional, but both `np.ones()` and `np.zeros()` also allow us to create arrays of larger dimension. In the case below, we can perceive this as four 2D arrays in which each consists of 5 rows and 6 columns.

In [31]:
# Codeblock 32
np.zeros((4,5,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

If you’re familiar with matrices, you might often heard the term “identity matrix.” Numpy provides a function to create this kind of matrix through `np.identity()`. In Codeblock 33 I create an identity matrix of size `6×6`.

In [32]:
# Codeblock 33
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Keep in mind that `np.identity()` can only form a square matrix. If you need to create a similar one yet with more flexibilities, you can use `np.eye()` instead. `np.eye()` allows us to control the height (`N`) and width (`M`) of the matrix as well as the offset of the diagonal (`k`). In the subsequent example I set the matrix size to 6×4 with the diagonal offset of 1 (meaning that the ones are shifted to the right once).

In [33]:
# Codeblock 34
np.eye(N=6, M=4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

`np.diag()`, on the other hand, creates an array which the elements in diagonal can be defined manually. It is also possible to use the `k` parameter for this function.

In [34]:
# Codeblock 35
np.diag([1,4,3,4,4])

array([[1, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 4]])

The next one I want to show you is `np.empty()`. Actually I found this function interesting because the resulting output looks like a random value. In fact, it is not intended for generating random numbers, rather, it basically takes the value of the current memory state. This approach is useful if you want to allocate an empty array to be filled later but you’re very concerned to the computation time. According to my experiment, `np.ones()` is a lot slower than both `np.zeros()` and `np.empty()`. `np.empty()` itself is indeed slightly faster than `np.zeros()`.

In [35]:
# Codeblock 36
np.empty((3,3))

array([[4.83568256e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

If you need a function which has the similar behavior to `np.zeros()` and `np.ones()` yet with the number that you can specify on your own, then you can use `np.full()`. The subsequent codeblock shows how I use the function to create an array of size 3×5 which the elements are all 999.

In [36]:
# Codeblock 37
J = np.full(shape=(3,5), fill_value=999)
J

array([[999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999]])

In case you need to create an array consisting of a specific number and at the same time you also want it to have the same shape of another existing array, you can use either `np.full_like()`, `np.empty_like()`, `np.ones_like()` or `np.zeros_like()`. Well, it might sound a bit confusing at first, but you will understand once you see the following example.

In [37]:
# Codeblock 38
np.full_like(J, fill_value=111)

array([[111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111]])

In the above case, `np.full_like()` takes the shape of array `J`, which is `(3,5)`. Then, it sets the value of all elements to 111. Similar thing also applies to the other three functions except that we don’t need to use the `fill_value` parameter. As you can see the output in Figure 37, all the resulting arrays have the same shape as `J`.

In [38]:
# Codeblock 39
print(np.empty_like(J), end='\n\n')
print(np.ones_like(J), end='\n\n')
print(np.zeros_like(J))

[[97875305807232              0              0              0
               0]
 [             0              0              0              0
               0]
 [             0              0              0              0
               0]]

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# Sequential Numbers

Now let’s discuss how we can create an array of sequential numbers using Numpy. The first function for this purpose is `np.arange()`. This function is actually similar to the Python’s `range()`. What makes the two different is that `np.arange()` automatically generates an array, while `range()` is an iterator. The Codeblock 40 below shows how to use `np.arange()` to create an array containing the number 0 to 19.

In [39]:
# Codeblock 40
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In order to create the same thing using `range()`, we need to write it down like this:

In [40]:
# Codeblock 41
[i for i in range(20)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

Despite this difference in behavior, the parameters available to be set are exactly the same, namely `start`, `stop`, and `step`, respectively. Keep in mind that the number we specify for the stop is not going to get included in the sequence. The following codeblock shows some examples of how we can use `np.arange()`.

In [41]:
# Codeblock 42
print(np.arange(3, 20, 2), end='\n\n')
print(np.arange(100, 0, -3), end='\n\n')
print(np.arange(20, 30, 0.5))

[ 3  5  7  9 11 13 15 17 19]

[100  97  94  91  88  85  82  79  76  73  70  67  64  61  58  55  52  49
  46  43  40  37  34  31  28  25  22  19  16  13  10   7   4   1]

[20.  20.5 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5
 27.  27.5 28.  28.5 29.  29.5]


In fact, there is one advantage of `np.arange()` over the `range()` function: it allows us to pass a float to the parameters like what I did in the last example in Codeblock 42.

Another Numpy function to generate sequential number is `np.linspace()` which basically stands for linear space. The first two params of this function are `start` and `stop`, just like `np.arange()`. However, the third one is different, in which `np.linspace()` uses `num` to control the number of elements we want to generate. In the following example I set the function such that it writes down 50 numbers stretched evenly from 1 to 15. Notice that the `stop` parameter of `np.linspace()` has different behavior from `np.arange()`, in a sense that the number passed into it is included in the array.

In [42]:
# Codeblock 43
np.linspace(1, 15, 50)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

There is a similar function named `np.geomspace()` which I actually never use. Rather than following linear scale, the distribution of the numbers follows a geometric scale instead. Below is an example of how to use the function.

In [43]:
# Codeblock 44
np.geomspace(1, 15, 50)

array([ 1.        ,  1.05682204,  1.11687283,  1.18033582,  1.24740491,
        1.318285  ,  1.39319265,  1.4723567 ,  1.55601901,  1.64443519,
        1.73787535,  1.83662498,  1.94098576,  2.05127653,  2.16783425,
        2.29101502,  2.42119517,  2.55877242,  2.70416709,  2.85782339,
        3.02021075,  3.19182529,  3.37319131,  3.56486293,  3.76742572,
        3.98149854,  4.20773541,  4.44682753,  4.69950535,  4.96654083,
        5.24874982,  5.5469945 ,  5.86218605,  6.19528743,  6.54731631,
        6.91934818,  7.31251967,  7.72803197,  8.16715452,  8.63122891,
        9.12167296,  9.63998503, 10.18774866, 10.76663734, 11.37841965,
       12.02496468, 12.70824772, 13.43035629, 14.19349655, 15.        ])

# Credit:

https://python.plainenglish.io/mastering-numpy-a-comprehensive-guide-to-efficient-array-processing-part-1-2-d55efd851234